---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Mahadevan Subramanian"
keywords:    "Mahadevan Subramanian, IIT Bombay, SinglePaged, jekyll, github, single page"
description: "A single-page template for Jekyll based blogs (like what you'd use on github pages!)"
source_link: "https://github.com/mahadevans2432/mahadevans2432.github.io"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#f6f9fB' #Changed to a white shade for dark mode
  white:     '#111111' #Changed to a black shade for dark mode
  blue:      '#459fae' #Changed to a duller shade of blue
  green:     '#28a442' #Changed to a nicer green
  purple:    '#6b0761' #Changed to a darker purple shade
  orange:    '#a93838' #Changed to maroonish shade
  turquoise: '#17946f' #Changed to a darker greener shade

kramdown:
  auto_ids:  false

